config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :parts
  resources :cars_parts
  #root 'pages#index'
  root 'cars_parts#index'
  get 'cars_parts/index'
  resources :cars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
	has_and_belongs_to_many :parts
	belongs_to :cars_parts
	validates :make, :model, :vin, :year, presence: true
	validates :year, numericality: {greater_than_or_equal_to: 1885}

end

app/models/cars_part.rb
class CarsPart < ApplicationRecord
	has_many :car
end

app/models/part.rb
class Part < ApplicationRecord
	has_and_belongs_to_many :cars
	validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
     @cars = if params[:term]
      Car.where('name LIKE ?', "%#{params[:term]}%")
    else
      Car.all
    end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:make, :model, :vin, :year, :term, part_ids: [])
    end
end

app/controllers/cars_parts_controller.rb
class CarsPartsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token
  before_action :set_cars_part, only: [:show, :edit, :update, :destroy]

  # GET /cars_parts
  # GET /cars_parts.json
  def index
    @cars_parts = CarsPart.all
  end

  # GET /cars_parts/1
  # GET /cars_parts/1.json
  def show
  end

  # GET /cars_parts/new
  def new
    @cars_part = CarsPart.new
  end

  # GET /cars_parts/1/edit
  def edit
  end

  # POST /cars_parts
  # POST /cars_parts.json
  def create
    @cars_part = CarsPart.new(cars_part_params)

    respond_to do |format|
      if @cars_part.save
        format.html { redirect_to @cars_part, notice: 'Cars part was successfully created.' }
        format.json { render :show, status: :created, location: @cars_part }
      else
        format.html { render :new }
        format.json { render json: @cars_part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars_parts/1
  # PATCH/PUT /cars_parts/1.json
  def update
    respond_to do |format|
      if @cars_part.update(cars_part_params)
        format.html { redirect_to @cars_part, notice: 'Cars part was successfully updated.' }
        format.json { render :show, status: :ok, location: @cars_part }
      else
        format.html { render :edit }
        format.json { render json: @cars_part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars_parts/1
  # DELETE /cars_parts/1.json
  def destroy
    @cars_part.destroy
    respond_to do |format|
      format.html { redirect_to cars_parts_url, notice: 'Cars part was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cars_part
      @cars_part = CarsPart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cars_part_params
      params.fetch(:cars_part, {})
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
before_action :authenticate_user!
  def home
  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token
  before_action :set_part, only: [:show, :edit, :update, :destroy]

  # GET /parts
  # GET /parts.json
  def index
    
    @parts = if params[:term]
      Part.where('name LIKE ?', "%#{params[:term]}%")
    else
      Part.all
    end
    
  end

  # GET /parts/1
  # GET /parts/1.json
  def show
  end

  # GET /parts/new
  def new
    @part = Part.new
  end

  # GET /parts/1/edit
  def edit
  end

  # POST /parts
  # POST /parts.json
  def create
    @part = Part.new(part_params)
    @parts = Part.all

    respond_to do |format|
      if @part.save
        format.html { redirect_to @part, notice: 'Part was successfully created.' }
        format.json { render :show, status: :created, location: @part }
      else
        format.html { render :new }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1
  # PATCH/PUT /parts/1.json
  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to @part, notice: 'Part was successfully updated.' }
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render :edit }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.json
  def destroy
    @part.destroy
    respond_to do |format|
      format.html { redirect_to parts_url, notice: 'Part was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part
      @part = Part.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def part_params
      params.require(:part).permit(:name, :term)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/cars_parts_helper.rb
module CarsPartsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :make %>
    <%= form.text_field :make %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :vin %>
    <%= form.text_field :vin %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>

     <div class="field">
   <%= form.label "Parts", class: 'control-label'%>
      <div class="controls">
       <%= form.collection_select :part, Part.all.map, :id, :name, {:include_blank => false}, {:multiple => true} %>
       
      </div>
    </div> 



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_parts_path %>

app/views/cars/index.html.erb
<%= link_to 'Home', cars_parts_path %>
<%= link_to 'Cars', cars_path%>
<%= link_to'Parts', parts_path %>
<%= link_to 'Log out', destroy_user_session_path, method: :delete %>

<p id="notice"><%= notice %></p>

<h1>Cars</h1>

<table>
  <thead>
    <tr>
      <th>Make</th>
      <th>Model</th>
      <th>Vin</th>
      <th>Year</th>
      <th>Parts</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  
  <%= form_tag(parts_path, method: :get) do %>
  <%= text_field_tag :term, params[:term] %>
  <%= submit_tag 'Search', name: nil%>
  <% end %>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.make %></td>
        <td><%= car.model %></td>
        <td><%= car.vin %></td>
        <td><%= car.year %></td>
        <td><%= car.parts %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>
<%= link_to 'Back', cars_parts_path %>

app/views/cars/new.html.erb
<%= link_to 'Home', cars_parts_path %>
<%= link_to 'Cars', cars_path%>
<%= link_to'Parts', parts_path %>

<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_parts_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Make:</strong>
  <%= @car.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Vin:</strong>
  <%= @car.vin %>
</p>

<p>
  <strong>Year:</strong>
  <%= @car.year %>
</p>

<p>
  <strong>Parts:</strong>
  <%= @car.parts %>
</p>


<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_parts_path %>

app/views/cars_parts/_form.html.erb
<%= form_with(model: cars_part, local: true) do |form| %>
  <% if cars_part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cars_part.errors.count, "error") %> prohibited this cars_part from being saved:</h2>

      <ul>
      <% cars_part.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cars_parts/edit.html.erb
<h1>Editing Cars Part</h1>

<%= render 'form', cars_part: @cars_part %>

<%= link_to 'Show', @cars_part %> |
<%= link_to 'Back', cars_parts_path %>

app/views/cars_parts/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Home', cars_parts_path %>
<%= link_to 'Cars', cars_path%>
<%= link_to'Parts', parts_path %>
<%= link_to 'Log out', destroy_user_session_path, method: :delete %>

<h1>Cars Parts Home Page</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars_parts.each do |cars_part| %>
      <tr>
        <td><%= link_to 'Show', cars_part %></td>
        <td><%= link_to 'Edit', edit_cars_part_path(cars_part) %></td>
        <td><%= link_to 'Destroy', cars_part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>
<%= link_to 'New Part', new_part_path %>

app/views/cars_parts/new.html.erb
<h1>New Cars Part</h1>

<%= render 'form', cars_part: @cars_part %>

<%= link_to 'Back', cars_parts_path %>

app/views/cars_parts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_cars_part_path(@cars_part) %> |
<%= link_to 'Back', cars_parts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarsParts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>

   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>


</html>

app/views/parts/_form.html.erb
<%= form_with(model: part, local: true) do |form| %>
  <% if part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(part.errors.count, "error") %> prohibited this part from being saved:</h2>

      <ul>
      <% part.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/parts/edit.html.erb
<h1>Editing Part</h1>

<%= render 'form', part: @part %>

<%= link_to 'Show', @part %> |
<%= link_to 'Back', cars_parts_path %>

app/views/parts/index.html.erb
<%= link_to 'Home', cars_parts_path %>
<%= link_to 'Cars', cars_path%>
<%= link_to'Parts', parts_path %>
<%= link_to 'Log out', destroy_user_session_path, method: :delete %>

<p id="notice"><%= notice %></p>

<h1>Parts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <%= form_tag(parts_path, method: :get) do %>
  <%= text_field_tag :term, params[:term] %>
  <%= submit_tag 'Search', name: nil%>
  <% end %>


  <tbody>
    <% @parts.each do |part| %>
      <tr>
        <td><%= part.name %></td>
        <td><%= link_to 'Show', part %></td>
        <td><%= link_to 'Edit', edit_part_path(part) %></td>
        <td><%= link_to 'Destroy', part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Part', new_part_path %>
<%= link_to 'Back', cars_parts_path %>

app/views/parts/new.html.erb
<%= link_to 'Home', cars_parts_path %>
<%= link_to 'Cars', cars_path%>
<%= link_to'Parts', parts_path %>

<h1>New Part</h1>

<%= render 'form', part: @part %>

<%= link_to 'Back', cars_parts_path %>

app/views/parts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @part.name %>
</p>

<%= link_to 'Edit', edit_part_path(@part) %> |
<%= link_to 'Back', parts_path %>